"""Probe a live Mitos MCP server and write the capability matrix from what it reports.

Phase 1 of the product plan requires a *confirmed* capability matrix. That cannot
be written by hand or inferred: it has to come from a running server. This module
connects, calls `tools/list`, and renders `docs/mitos.md` from the response.

It deliberately refuses to emit a matrix when no server answers, so an unverified
document can never masquerade as a verified one.

    python -m app.probe_mitos --command "<command that starts the Mitos MCP server>"
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from .config import settings
from .execution.mitos import DEFAULT_TOOL_MAP, McpStdioClient

# What the executor needs a tool for, and what it must be able to express.
REQUIRED_CAPABILITIES = {
    "connect_pins": "Join two named component pins onto one net",
    "connect_pin_to_net": "Join one component pin to an existing named net",
    "add_component": "Place a symbol and connect both of its terminals",
    "read_schematic": "Read back components, pins and nets",
}

# Substrings that suggest a discovered tool serves a required capability. Only a
# hint for the report - a human still confirms the mapping.
HINTS = {
    "connect_pins": ("connect_pin", "connect", "wire", "net"),
    "connect_pin_to_net": ("pin_to_net", "connect", "net", "label"),
    "add_component": ("add_component", "add_symbol", "place", "component", "symbol"),
    "read_schematic": ("read", "get", "list", "schematic", "inspect"),
}


class ProbeError(RuntimeError):
    pass


def probe(command: str) -> list[dict]:
    try:
        with McpStdioClient(command) as client:
            return client.list_tools()
    except Exception as exc:  # noqa: BLE001 - any failure means "not confirmed"
        raise ProbeError(f"could not probe the Mitos MCP server via {command!r}: {exc}") from exc


def _candidates(capability: str, tools: list[dict]) -> list[str]:
    names = [str(tool.get("name", "")) for tool in tools]
    hints = HINTS.get(capability, ())
    scored = [
        (min((i for i, h in enumerate(hints) if h in name.lower()), default=len(hints)), name)
        for name in names
    ]
    return [name for rank, name in sorted(scored) if rank < len(hints)]


def render_matrix(command: str, tools: list[dict]) -> str:
    lines = [
        "# Mitos capability matrix (probed)",
        "",
        "<!-- GENERATED by `python -m app.probe_mitos`. Do not hand-edit: re-run the probe. -->",
        "",
        f"Generated by `python -m app.probe_mitos` from a live server started with `{command}`.",
        f"The server advertised **{len(tools)} tool(s)**. Re-run the probe whenever the server changes.",
        "",
        "> **What this does and does not confirm.** Everything below was read from a running server's",
        "> `tools/list`, so the adapter, the tool contract and the argument shapes are verified against",
        "> something real rather than guessed. It says nothing about any *other* server: if the command",
        "> above is this repo's own `app.mcp_server`, then the third-party Mitos server remains",
        "> unconfirmed, and confirming it means re-running this probe against it. The tool names are",
        "> configurable for exactly that reason.",
        "",
        "## What the executor needs",
        "",
        "| Backend action | Requirement | Configured tool | Advertised? | Candidates on this server |",
        "| --- | --- | --- | --- | --- |",
    ]
    advertised = {str(tool.get("name", "")) for tool in tools}
    for capability, requirement in REQUIRED_CAPABILITIES.items():
        configured = DEFAULT_TOOL_MAP.get(capability, "-")
        present = "yes" if configured in advertised else "**no**"
        candidates = ", ".join(f"`{name}`" for name in _candidates(capability, tools)[:4]) or "-"
        lines.append(f"| `{capability}` | {requirement} | `{configured}` | {present} | {candidates} |")

    lines += ["", "## Tools the server advertises", ""]
    if not tools:
        lines.append("The server advertised no tools.")
    for tool in tools:
        name = tool.get("name", "?")
        lines += [f"### `{name}`", "", str(tool.get("description") or "_no description_"), ""]
        schema = tool.get("inputSchema") or tool.get("input_schema")
        if schema:
            required = set(schema.get("required") or [])
            properties = schema.get("properties") or {}
            if properties:
                lines += ["| Argument | Type | Required | Description |", "| --- | --- | --- | --- |"]
                for arg, spec in properties.items():
                    spec = spec if isinstance(spec, dict) else {}
                    lines.append(
                        f"| `{arg}` | {spec.get('type', 'any')} | "
                        f"{'yes' if arg in required else 'no'} | {spec.get('description', '')} |"
                    )
            else:
                lines += ["```json", json.dumps(schema, indent=2), "```"]
            lines.append("")

    unmapped = sorted(advertised - set(DEFAULT_TOOL_MAP.values()))
    if unmapped:
        lines += [
            "## Advertised but unused by this backend",
            "",
            ", ".join(f"`{name}`" for name in unmapped),
            "",
        ]
    lines += [
        "## Still to confirm by hand",
        "",
        "1. Whether each mapped tool writes to disk immediately (ERC runs on the saved file).",
        "2. Whether adding a symbol and connecting it is one call or place-then-connect.",
        "3. Whether a Mitos-side undo exists, or the file-level checkpoint stays the rollback.",
        "4. Whether the current KiCAD selection is readable, which would enable §5.2 live selection.",
        "5. Whether PCB edits are supported, which is what makes the DRC gate meaningful.",
        "",
    ]
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--command",
        default=settings.mitos_command,
        help="command that starts the Mitos MCP server on stdio",
    )
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[2] / "docs" / "mitos.md",
        help="capability matrix to write",
    )
    args = parser.parse_args(argv)

    if not args.command:
        print(
            "No Mitos command configured. Pass --command or set KICAD_MITOS_MITOS_COMMAND.\n"
            "Refusing to write a capability matrix that was not probed from a live server.",
            file=sys.stderr,
        )
        return 2
    try:
        tools = probe(args.command)
    except ProbeError as exc:
        print(
            f"{exc}\nNothing was written; the existing matrix still reflects the last confirmed state.",
            file=sys.stderr,
        )
        return 1

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render_matrix(args.command, tools) + "\n")
    print(f"probed {len(tools)} tool(s) -> {args.out}")
    for tool in tools:
        print(f"  - {tool.get('name')}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
